export const GET_FEATURES_REQUEST = 'GET_FEATURES_REQUEST';
export const GET_FEATURES_SUCCESS = 'GET_FEATURES_SUCCESS';
export const GET_FEATURES_FALIURE = 'GET_FEATURES_FALIURE';
export const UPDATE_FEATURE_LIST = 'UPDATE_FEATURE_LIST';
export const VIN_NUMBER = 'VIN_NUMBER';
